### PR TITLE
fix: polkit password prompts broken via SSH (#574)

### LINKED ISSUE #574: When running from a SSH session, PolicyKit password prompts are not masked when checking for Flatpak updates.
### Environment

arch-update 3.19.1
Arch Linux

### Arch-Update configuration

```text
TrayIconStyle=light
```

### Description of the bug

When running `arch-update` from an SSH session, PolicyKit password prompts (example for Flatpak) are no longer masked. Passwords are visible in plain-text on the shell.

### Screenshots / Logs

Image

```text
++ case "${option}" in
++ unset option
++ statedir=/home/amoore/.local/state/arch-update
++ tmpdir=/tmp/arch-update-1000
++ mkdir -p /home/amoore/.local/state/arch-update /tmp/arch-update-1000
++ checkupdates_db_tmpdir_prefix=/tmp/arch-update-1000/checkupdates-
++ . gettext.sh
+++ test 'X\t' = 'X\t'
+++ echo=echo
+++ test -z ''
+++ case "$0" in
++ export TEXTDOMAIN=Arch-Update
++ TEXTDOMAIN=Arch-Update
++ '[' -f /locale/fr/LC_MESSAGES/Arch-Update.mo ']'
++ '[' -f /home/amoore/.local/share/locale/fr/LC_MESSAGES/Arch-Update.mo ']'
++ '[' -f /home/amoore/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share/locale/fr/LC_MESSAGES/Arch-Update.mo ']'
++ '[' -f /usr/local/share/locale/fr/LC_MESSAGES/Arch-Update.mo ']'
++ '[' -z '' ']'
++ bold='\e[1m'
++ blue='\e[1m\e[34m'
++ green='\e[1m\e[32m'
++ yellow='\e[1m\e[33m'
++ red='\e[1m\e[31m'
++ color_off='\e[0m'
++ pacman_color_opt=always
++ '[' -z '' ']'
+++ command -v flatpak
++ flatpak_support=/usr/bin/flatpak
++ '[' -n /usr/bin/flatpak ']'
+++ flatpak list --user
+++ flatpak list --system
++ '[' -z $'TRUNCATED']
++ '[' -z '' ']'
+++ command -v notify-send
++ notification_support=/usr/bin/notify-send
++ '[' -z '' ']'
+++ command -v alhp.utils
++ alhp_support=
++ trap cleanup EXIT
+ case "${option}" in
+ check_su_cmd
+ '[' -z '' ']'
+ command -v sudo
+ su_cmd=sudo
+ check_aur_helper
+ '[' -z '' ']'
+ '[' -z '' ']'
+ command -v paru
+ command -v yay
+ aur_helper=yay
+ check_diff_prog
+ '[' -n '' ']'
+ '[' -n '' ']'
+ source /usr/share/arch-update/lib/full_upgrade.sh
++ exec
++ flock -n 10
++ source /usr/share/arch-update/lib/list_packages.sh
++++ eval_gettext 'Looking for updates...\n'
++++ gettext 'Looking for updates...\n'
+++++ envsubst --variables 'Looking for updates...\n'
++++ export PATH
++++ envsubst 'Looking for updates...\n'
+++ info_msg 'Looking for updates...\n'
+++ msg='Looking for updates...\n'
+++ echo -e '\e[1m\e[32m==>\e[0m\e[1m Looking for updates...\n\e[0m'
==> Looking for updates...

++++ mktemp -d /tmp/arch-update-1000/checkupdates-XXXXX
+++ checkupdates_db_tmpdir=/tmp/arch-update-1000/checkupdates-Vczl9
++++ CHECKUPDATES_DB=/tmp/arch-update-1000/checkupdates-Vczl9
++++ timeout 30 checkupdates
+++ packages=$'TRUNCATED'
+++ packages_exit_code=0
+++ '[' 0 -eq 124 ']'
+++ '[' -n '' ']'
+++ '[' -n yay ']'
++++ timeout 30 yay --color always -Qua
+++ unformatted_aur_packages=
+++ unformatted_aur_packages_exit_code=1
++++ echo ''
++++ sed 's/^ *//'
++++ sed 's/ \+/ /g'
++++ grep -vw '\[ignored\]$'
+++ aur_packages=
+++ '[' 1 -eq 124 ']'
+++ '[' -n '' ']'
+++ '[' -n /usr/bin/flatpak ']'
+++ timeout 30 flatpak update --appstream
```

### Additional context

This is a recent occurrence.

### PR DESCRIPTION
**Pull request by FineWolf**
### Description

Added `--foreground/-f` flag to `timeout` calls in the list-packages routine to fix polkit password prompts when used via SSH.

### Screenshots / Logs

See #574

### Fixed bug

Fixes #574 

### Notes

Sorry for the delay, I was already off my computer for the day by the time you asked me for a PR.

### CODE REVIEW

File: src/lib/list_packages.sh [hunk 1]
```diff
@@ -37,7 +37,7 @@ if [ -n "${aur_helper}" ]; then
 fi
 
 if [ -n "${flatpak_support}" ]; then
-	timeout "${update_check_timeout}" flatpak update --appstream > /dev/null
+	timeout -f "${update_check_timeout}" flatpak update --appstream > /dev/null
```
Comment (Antiz96) [inline src/lib/list_packages.sh]:
```suggestion
	timeout --foreground "${update_check_timeout}" flatpak update --appstream > /dev/null
```

Purely a personal preference, but I'd prefer to use the long opt here.

File: src/lib/list_packages.sh [hunk 2]
```diff
@@ -9,7 +9,7 @@ info_msg "$(eval_gettext "Looking for updates...\n")"
 # shellcheck disable=SC2154
 checkupdates_db_tmpdir=$(mktemp -d "${checkupdates_db_tmpdir_prefix}XXXXX")
 # shellcheck disable=SC2154
-packages=$(CHECKUPDATES_DB="${checkupdates_db_tmpdir}" timeout "${update_check_timeout}" checkupdates "${contrib_color_opt[@]}")
+packages=$(CHECKUPDATES_DB="${checkupdates_db_tmpdir}" timeout -f "${update_check_timeout}" checkupdates "${contrib_color_opt[@]}")
```
Comment (Antiz96) [inline src/lib/list_packages.sh]: The `--foreground` option shouldn't be needed in this case. I'm not sure what's better here, consistently use the `--foreground` option everywhere or only apply it when strictly needed? Any thoughts? I'm kinda leaning toward the latter but please let me know if you think otherwise.

File: src/lib/list_packages.sh [hunk 3]
```diff
@@ -24,7 +24,7 @@ if [ -n "${aur_helper}" ]; then
 	# The former because it assumes an interactive TTY environment (causing `timeout` to behave unexpectedly) 
 	# The latter because it outputs some descriptive string in stderr when looking for updates with -Qua
 	# shellcheck disable=SC2154
-	unformatted_aur_packages=$(timeout "${update_check_timeout}" "${aur_helper}" --color "${pacman_color_opt}" "${devel_flag[@]}" -Qua < /dev/null 2> /dev/null)
+	unformatted_aur_packages=$(timeout -f "${update_check_timeout}" "${aur_helper}" --color "${pacman_color_opt}" "${devel_flag[@]}" -Qua < /dev/null 2> /dev/null)
```
Comment (Antiz96) [inline src/lib/list_packages.sh]: The `--foreground` option shouldn't be needed in this case. I'm not sure what's better here, consistently use the `--foreground` option everywhere or only apply it when strictly needed? Any thoughts? I'm kinda leaning toward the latter but please let me know if you think otherwise.

**Review by Antiz96 — COMMENTED** [review]
Thanks a lot! No worries for the delay, I wasn't expecting the PR that fast actually 😄 

Just a few questions / suggestions, see below.

File: src/lib/list_packages.sh (hunk 3 above)
Comment (FineWolf) [reply src/lib/list_packages.sh]: I tend to value the latter as well. Applying patterns even when not strictly needed tend to lower the mental load of maintaining a code base in the long run.

File: src/lib/list_packages.sh (hunk 2 above)
Comment (FineWolf) [reply src/lib/list_packages.sh]: I tend to value the latter as well. Applying patterns even when not strictly needed tend to lower the mental load of maintaining a code base in the long run.

Comment (Antiz96) [reply src/lib/list_packages.sh]: Ah, I meant the latter as in "only apply it when strictly needed" on my side :yum:

While the flatpak command becomes interactive when executed in a TTY / SSH environment, the `checkupdates` and `<aur_helper> -Qua` ones should never be. I'm not found of allowing those to read TTY inputs (and taking the risk of eventual children commands to not be timed out) if not strictly necessary. I think I'd therefore rather keep the `--foreground` option exclusive to the flatpak command, which is the only one that should actually need it here.

Comment (FineWolf) [reply src/lib/list_packages.sh]: Done

**Review by Antiz96 — APPROVED** [review]
Thanks a lot!
I'll cut a new release shortly.

**Comment by Antiz96** [comment]
Fix included in the latest [v3.19.2 release](https://github.com/Antiz96/arch-update/releases/tag/v3.19.2).  
Thanks again for the PR!
